source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"
use_frameworks!
target 'MiaoBo' do
pod 'ReactiveCocoa', '~> 2.5'
pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 4.0.0'
pod 'MJRefresh', '~> 3.1.12'
pod 'MJExtension', '~> 3.0.13'
pod 'Masonry', '~> 1.0.2'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'BarrageRenderer', '~> 1.9.1'
#pod 'GPUImage', '~> 0.1.7' 由于LFLiveKit里面已经集成了GPUImage
pod 'LFLiveKit', '~> 1.6'
//http://bojuesk.com:8080/channel/url/editallurlbyname?name=zlyurl
//http://192.168.1.109:8080/wjamm/
end
