platform :ios, ‘9.0’

target "zly-ofo" do
use_frameworks!
pod 'SWRevealViewController'
pod 'SnapKit', '~> 3.2.0'
pod 'AMap3DMap'
pod 'AMapSearch'
pod 'AMapLocation'
pod 'AMapNavi'
pod 'FTIndicator'
pod 'swiftScan'
pod 'APNumberPad'
pod 'SwiftyTimer'
pod 'SwiftySound'
pod 'AVOSCloud'
pod 'MIBlurPopup'
end
